# Generated by Django 6.0.1 on 2026-01-18 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='接口名称')),
                ('path', models.CharField(max_length=200, verbose_name='接口路径')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10, verbose_name='请求方法')),
                ('category', models.CharField(max_length=50, verbose_name='接口分类')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('params', models.TextField(blank=True, verbose_name='请求参数')),
                ('headers', models.TextField(blank=True, verbose_name='请求头')),
                ('response', models.TextField(blank=True, verbose_name='响应示例')),
                ('timeout', models.IntegerField(default=5000, verbose_name='超时时间(ms)')),
                ('permission', models.CharField(blank=True, max_length=100, verbose_name='权限标识')),
                ('require_auth', models.BooleanField(default=True, verbose_name='需要认证')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'API配置',
                'verbose_name_plural': 'API配置列表',
                'db_table': 'system_api',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='流程名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('nodes', models.JSONField(default=list, verbose_name='节点配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'system_flow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200, verbose_name='路由路径')),
                ('name', models.CharField(max_length=100, verbose_name='路由名称')),
                ('component', models.CharField(max_length=200, verbose_name='组件路径')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='标题')),
                ('hidden', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('keep_alive', models.BooleanField(default=True, verbose_name='是否缓存')),
                ('sort', models.IntegerField(default=1, verbose_name='排序')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'system_route',
                'ordering': ['sort', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('path', models.CharField(blank=True, max_length=200, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, max_length=200, verbose_name='组件路径')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('type', models.CharField(choices=[('menu', '菜单'), ('button', '按钮')], default='menu', max_length=10, verbose_name='类型')),
                ('permission', models.CharField(blank=True, max_length=100, verbose_name='权限标识')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_external', models.BooleanField(default=False, verbose_name='是否外链')),
                ('keep_alive', models.BooleanField(default=False, verbose_name='是否缓存')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system.menu', verbose_name='父级菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单列表',
                'db_table': 'system_menu',
                'ordering': ['sort', 'created_at'],
            },
        ),
    ]
