# Generated by Django 6.0.1 on 2026-01-18 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True, verbose_name='物品编号')),
                ('item_name', models.CharField(max_length=100, verbose_name='物品名称')),
                ('category', models.CharField(choices=[('电子产品', '电子产品'), ('办公用品', '办公用品'), ('机械设备', '机械设备'), ('日用品', '日用品'), ('其他', '其他')], max_length=20, verbose_name='分类')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格型号')),
                ('unit', models.CharField(choices=[('个', '个'), ('件', '件'), ('台', '台'), ('箱', '箱'), ('套', '套')], default='个', max_length=10, verbose_name='单位')),
                ('initial_stock', models.IntegerField(default=0, verbose_name='初始库存')),
                ('current_stock', models.IntegerField(default=0, verbose_name='当前库存')),
                ('min_stock', models.IntegerField(default=10, verbose_name='最低库存预警')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='存放位置')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品列表',
                'db_table': 'warehouse_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('supplier', models.CharField(max_length=100, verbose_name='供应商')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('inbound_date', models.DateField(verbose_name='入库日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.item', verbose_name='物品')),
            ],
            options={
                'verbose_name': '入库记录',
                'verbose_name_plural': '入库记录列表',
                'db_table': 'warehouse_inbound',
                'ordering': ['-inbound_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('receiver', models.CharField(max_length=100, verbose_name='领用人')),
                ('outbound_date', models.DateField(verbose_name='出库日期')),
                ('reason', models.TextField(verbose_name='出库原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.item', verbose_name='物品')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
            ],
            options={
                'verbose_name': '出库记录',
                'verbose_name_plural': '出库记录列表',
                'db_table': 'warehouse_outbound',
                'ordering': ['-outbound_date', '-created_at'],
            },
        ),
    ]
