# Generated by Django 6.0.1 on 2026-01-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboundrecord',
            name='price',
        ),
        migrations.RemoveField(
            model_name='inboundrecord',
            name='total_amount',
        ),
    ]
