# Generated by Django 6.0.1 on 2026-01-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_inboundrecord_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=20, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(default='个', max_length=10, verbose_name='单位'),
        ),
    ]
