# Generated by Django 6.0.1 on 2026-01-18 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(max_length=50, unique=True, verbose_name='工号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('department', models.CharField(max_length=100, verbose_name='作业区/科室')),
                ('category', models.CharField(choices=[('正式员工', '正式员工'), ('临时员工', '临时员工'), ('实习生', '实习生'), ('合同工', '合同工')], max_length=20, verbose_name='人员类别')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'users_employee',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='部门')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='职位')),
                ('avatar', models.CharField(blank=True, max_length=200, verbose_name='头像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料列表',
                'db_table': 'user_profile',
            },
        ),
    ]
