# Generated by Django 6.0.1 on 2026-01-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_admin_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='level',
        ),
    ]
